const anime_raw = [
  { c: "Anime & Manga", q: "What is the name of the nine-tailed fox sealed inside Naruto?", o: ["Shukaku", "Matatabi", "Kurama", "Gyuki"], a: 2, e: "Kurama is the Nine-Tails.", i: "https://images.unsplash.com/photo-1578632292335-df3fbc186619?auto=format&fit=crop&w=500&q=60" },
  { c: "Anime & Manga", q: "In Attack on Titan, who is the creator of the Titans?", o: ["Ymir Fritz", "Eren Yeager", "Grisha Yeager", "Zeke"], a: 0, e: "Ymir Fritz is the founding titan." },
  { c: "Anime & Manga", q: "What is the highest bounty in One Piece (currently known)?", o: ["Gol D. Roger", "Whitebeard", "Kaido", "Shanks"], a: 0, e: "Gol D. Roger had a bounty of over 5.5 billion berries." },
  { c: "Anime & Manga", q: "Whose name is written first in Light Yagami's Death Note?", o: ["L", "Kurou Otoharada", "Raye Penber", "Naomi Misora"], a: 1, e: "Kurou Otoharada, a hostage taker, was his first test." },
  { c: "Anime & Manga", q: "What anime features brothers Edward and Alphonse Elric?", o: ["Fairy Tail", "Blue Exorcist", "Fullmetal Alchemist", "Soul Eater"], a: 2, e: "Fullmetal Alchemist (Brotherhood)." },
  { c: "Anime & Manga", q: "What is the name of Goku's signature attack?", o: ["Spirit Bomb", "Kamehameha", "Destructo Disc", "Special Beam Cannon"], a: 1, e: "The Kamehameha wave." },
  { c: "Anime & Manga", q: "In My Hero Academia, what is Izuku Midoriya's quirk called?", o: ["All For One", "One For All", "Explosion", "Half-Cold Half-Hot"], a: 1, e: "One For All, passed down by All Might." },
  { c: "Anime & Manga", q: "Which anime features a notebook that can kill anyone whose name is written in it?", o: ["Code Geass", "Monster", "Death Note", "Bleach"], a: 2, e: "Death Note." },
  { c: "Anime & Manga", q: "What sport is featured in the anime Haikyuu!!?", o: ["Basketball", "Tennis", "Volleyball", "Swimming"], a: 2, e: "Haikyuu!! is about high school volleyball." },
  { c: "Anime & Manga", q: "Who is the main protagonist of Demon Slayer?", o: ["Inosuke", "Zenitsu", "Tanjiro", "Nezuko"], a: 2, e: "Tanjiro Kamado." },
  { c: "Anime & Manga", q: "In Hunter x Hunter, what is the name of the power system?", o: ["Nen", "Chakra", "Haki", "Mana"], a: 0, e: "Nen." },
  { c: "Anime & Manga", q: "Which anime follows the journey of Spike Spiegel on a spaceship called the Bebop?", o: ["Trigun", "Outlaw Star", "Cowboy Bebop", "Space Dandy"], a: 2, e: "Cowboy Bebop." },
  { c: "Anime & Manga", q: "What is the name of the virtual reality MMORPG in Sword Art Online?", o: ["ALfheim Online", "Sword Art Online", "Gun Gale Online", "Underworld"], a: 1, e: "Sword Art Online (SAO)." },
  { c: "Anime & Manga", q: "Which JoJo's Bizarre Adventure part features Jotaro Kujo as the main JoJo?", o: ["Phantom Blood", "Battle Tendency", "Stardust Crusaders", "Diamond is Unbreakable"], a: 2, e: "Part 3: Stardust Crusaders." },
  { c: "Anime & Manga", q: "In Jujutsu Kaisen, who is known as the strongest sorcerer?", o: ["Megumi Fushiguro", "Yuji Itadori", "Satoru Gojo", "Suguru Geto"], a: 2, e: "Satoru Gojo." },
  { c: "Anime & Manga", q: "What is the goal of Monkey D. Luffy in One Piece?", o: ["To become the strongest swordsman", "To become the Pirate King", "To find the All Blue", "To map the world"], a: 1, e: "To become the Pirate King by finding the One Piece." },
  { c: "Anime & Manga", q: "Which Studio Ghibli film features a moving castle?", o: ["Spirited Away", "Princess Mononoke", "Howl's Moving Castle", "My Neighbor Totoro"], a: 2, e: "Howl's Moving Castle." },
  { c: "Anime & Manga", q: "In Bleach, what is the name of Ichigo's Zanpakuto?", o: ["Zangetsu", "Senbonzakura", "Kyoka Suigetsu", "Hyorinmaru"], a: 0, e: "Zangetsu." },
  { c: "Anime & Manga", q: "What is the name of the protagonist in Tokyo Ghoul?", o: ["Kaneki Ken", "Touka Kirishima", "Hideyoshi Nagachika", "Shuu Tsukiyama"], a: 0, e: "Kaneki Ken." },
  { c: "Anime & Manga", q: "Which anime features giant mechas called Evas?", o: ["Gundam", "Code Geass", "Neon Genesis Evangelion", "Gurren Lagann"], a: 2, e: "Neon Genesis Evangelion." },
  { c: "Anime & Manga", q: "In Fairy Tail, what kind of magic does Natsu Dragneel use?", o: ["Ice-Make", "Celestial Spirit", "Fire Dragon Slayer", "Requip"], a: 2, e: "Fire Dragon Slayer magic." },
  { c: "Anime & Manga", q: "What is the ultimate goal of the Elric brothers in Fullmetal Alchemist?", o: ["To become State Alchemists", "To find their father", "To restore their bodies", "To defeat the Homunculi"], a: 2, e: "To restore their original bodies using the Philosopher's Stone." },
  { c: "Anime & Manga", q: "Which anime is about a boy who wants to become the Wizard King?", o: ["Fairy Tail", "Black Clover", "Magi", "Radiant"], a: 1, e: "Asta in Black Clover." },
  { c: "Anime & Manga", q: "In Code Geass, what is the name of Lelouch's alter ego?", o: ["Zero", "Suzaku", "Kallen", "C.C."], a: 0, e: "Zero." },
  { c: "Anime & Manga", q: "What is the name of the protagonist in Steins;Gate?", o: ["Kurisu Makise", "Rintarou Okabe", "Mayuri Shiina", "Itaru Hashida"], a: 1, e: "Rintarou Okabe (or Hououin Kyouma)." },
  { c: "Anime & Manga", q: "In Mob Psycho 100, what happens when Mob's explosion meter hits 100%?", o: ["He falls asleep", "He loses his powers", "He unleashes his full psychic power", "He turns into a spirit"], a: 2, e: "He unleashes his full psychic power based on a specific emotion." },
  { c: "Anime & Manga", q: "Which anime features a school where students gamble for social status?", o: ["No Game No Life", "Kakegurui", "Death Parade", "Kaiji"], a: 1, e: "Kakegurui." },
  { c: "Anime & Manga", q: "In One Punch Man, what is Saitama's hero rank at the beginning?", o: ["S-Class", "A-Class", "B-Class", "C-Class"], a: 3, e: "He starts at the bottom of C-Class." },
  { c: "Anime & Manga", q: "What is the name of the town in Diamond is Unbreakable (JoJo Part 4)?", o: ["Tokyo", "Cairo", "Morioh", "Naples"], a: 2, e: "The crazy, noisy, bizarre town of Morioh." },
  { c: "Anime & Manga", q: "Which anime is about a group of kids trying to escape an orphanage that raises them as demon food?", o: ["The Promised Neverland", "Made in Abyss", "Seraph of the End", "Deadman Wonderland"], a: 0, e: "The Promised Neverland." },
  { c: "Anime & Manga", q: "In Vinland Saga, who is Thorfinn trying to take revenge on?", o: ["Askeladd", "Thors", "Canute", "Thorkell"], a: 0, e: "Askeladd, who killed his father." },
  { c: "Anime & Manga", q: "What instrument does Kousei Arima play in Your Lie in April?", o: ["Violin", "Piano", "Cello", "Flute"], a: 1, e: "He is a prodigy pianist." },
  { c: "Anime & Manga", q: "In Re:Zero, what power does Subaru Natsuki have?", o: ["Return by Death", "Time Stop", "Fire Magic", "Invisibility"], a: 0, e: "He returns to a 'save point' when he dies." },
  { c: "Anime & Manga", q: "Which anime features a protagonist who is reincarnated as a slime?", o: ["Overlord", "That Time I Got Reincarnated as a Slime", "Mushoku Tensei", "Konosuba"], a: 1, e: "That Time I Got Reincarnated as a Slime (TenSura)." },
  { c: "Anime & Manga", q: "What is the name of the sport in Yuri!!! on Ice?", o: ["Hockey", "Speed Skating", "Figure Skating", "Curling"], a: 2, e: "Men's figure skating." },
  { c: "Anime & Manga", q: "In Tokyo Revengers, what does Takemichi travel back in time to do?", o: ["Save his middle school girlfriend", "Become a gang leader", "Prevent a war", "Win the lottery"], a: 0, e: "To save Hinata Tachibana from being killed by the Tokyo Manji Gang." },
  { c: "Anime & Manga", q: "Which anime features a family of spies, assassins, and telepaths pretending to be normal?", o: ["Spy x Family", "Kaguya-sama", "Buddy Daddies", "Hinamatsuri"], a: 0, e: "Spy x Family." },
  { c: "Anime & Manga", q: "What is the name of the protagonist's dog in Chainsaw Man?", o: ["Denji", "Pochita", "Aki", "Power"], a: 1, e: "Pochita, the Chainsaw Devil." },
  { c: "Anime & Manga", q: "In Dr. Stone, what happens to humanity?", o: ["They go extinct", "They are turned to stone", "They are enslaved by aliens", "They move to space"], a: 1, e: "A mysterious flash petrifies all humans." },
  { c: "Anime & Manga", q: "Which anime is about a volleyball team from Karasuno High School?", o: ["Kuroko's Basketball", "Free!", "Haikyuu!!", "Blue Lock"], a: 2, e: "Haikyuu!!" },
  { c: "Anime & Manga", q: "What is the name of the main character in Gintama?", o: ["Shinpachi", "Kagura", "Gintoki", "Katsura"], a: 2, e: "Gintoki Sakata." },
  { c: "Anime & Manga", q: "In Cyberpunk: Edgerunners, what is David Martinez's first major cyberware implant?", o: ["Gorilla Arms", "Mantis Blades", "Sandevistan", "Kiroshi Optics"], a: 2, e: "A military-grade Sandevistan speedware." },
  { c: "Anime & Manga", q: "Which anime features a girl named Violet who works as an Auto Memory Doll?", o: ["Violet Evergarden", "Vivy", "Frieren", "Plastic Memories"], a: 0, e: "Violet Evergarden." },
  { c: "Anime & Manga", q: "In Blue Lock, what sport is being played?", o: ["Volleyball", "Basketball", "Soccer/Football", "Baseball"], a: 2, e: "It's a fierce soccer striker training program." },
  { c: "Anime & Manga", q: "What is the highest-grossing anime film of all time?", o: ["Spirited Away", "Your Name", "Demon Slayer: Mugen Train", "Suzume"], a: 2, e: "Demon Slayer: Mugen Train broke all box office records." },
  { c: "Anime & Manga", q: "In No Game No Life, what is the world governed by?", o: ["Strength", "Magic", "Games", "Money"], a: 2, e: "Everything is decided through games." },
  { c: "Anime & Manga", q: "Which anime is known for its incredible rotoscoped dance sequence in its ending (Chika Dance)?", o: ["Oshi no Ko", "Kaguya-sama: Love is War", "Bocchi the Rock!", "My Dress-Up Darling"], a: 1, e: "Kaguya-sama: Love is War." },
  { c: "Anime & Manga", q: "What is the main character's name in Solo Leveling?", o: ["Jin-Woo", "Yoo Jin", "Gojo", "Baam"], a: 0, e: "Sung Jin-Woo." },
  { c: "Anime & Manga", q: "In Frieren: Beyond Journey's End, what race is Frieren?", o: ["Human", "Dwarf", "Demon", "Elf"], a: 3, e: "She is an elf with a near-immortal lifespan." },
  { c: "Anime & Manga", q: "What is the name of the first Opening song for Attack on Titan?", o: ["Unravel", "Guren no Yumiya", "Shinzou wo Sasageyo", "The Rumbling"], a: 1, e: "Guren no Yumiya by Linked Horizon." }
];

const ANIME_QUESTIONS = anime_raw.map(q => ({
  category: q.c,
  categoryColor: "#FF5E00",
  question: q.q,
  options: q.o,
  correctIndex: q.a,
  explanation: q.e,
  imageUrl: q.i,
  points: 100
}));

module.exports = { ANIME_QUESTIONS };
