const gk_raw = [
  { c: "General Knowledge", q: "What is the capital of Australia?", o: ["Sydney", "Melbourne", "Canberra", "Perth"], a: 2, e: "Canberra is the capital, chosen as a compromise between Sydney and Melbourne." },
  { c: "General Knowledge", q: "Listen to this animal sound. What animal is this?", o: ["Cat", "Dog", "Wolf", "Bear"], a: 1, e: "It's a dog barking.", u: "https://actions.google.com/sounds/v1/animals/dog_barking.ogg" },
  { c: "General Knowledge", q: "Which planet is known as the Red Planet?", o: ["Venus", "Jupiter", "Saturn", "Mars"], a: 3, e: "Mars is known as the Red Planet due to its iron oxide surface." },
  { c: "General Knowledge", q: "What is the largest ocean on Earth?", o: ["Atlantic", "Indian", "Arctic", "Pacific"], a: 3, e: "The Pacific Ocean is the largest and deepest ocean." },
  { c: "General Knowledge", q: "Who wrote the play 'Romeo and Juliet'?", o: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], a: 1, e: "William Shakespeare wrote it in the 1590s." },
  { c: "General Knowledge", q: "What is the hardest natural substance on Earth?", o: ["Gold", "Iron", "Diamond", "Platinum"], a: 2, e: "Diamond is the hardest naturally occurring substance." },
  { c: "General Knowledge", q: "What is the chemical symbol for Gold?", o: ["Ag", "Au", "Pb", "Fe"], a: 1, e: "Au, from the Latin word 'aurum'." },
  { c: "General Knowledge", q: "In what year did the Titanic sink?", o: ["1905", "1912", "1918", "1923"], a: 1, e: "The Titanic sank in 1912 on its maiden voyage." },
  { c: "General Knowledge", q: "What is the tallest mountain in the world?", o: ["K2", "Mount Kilimanjaro", "Mount Everest", "Denali"], a: 2, e: "Mount Everest, peaking at 8,848 meters." },
  { c: "General Knowledge", q: "Who painted the Mona Lisa?", o: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], a: 2, e: "Leonardo da Vinci painted it in the early 16th century." },
  { c: "General Knowledge", q: "Which element is said to keep bones strong?", o: ["Potassium", "Calcium", "Iron", "Zinc"], a: 1, e: "Calcium is essential for bone health." },
  { c: "General Knowledge", q: "What is the smallest country in the world?", o: ["Monaco", "Nauru", "San Marino", "Vatican City"], a: 3, e: "Vatican City is the smallest independent state." },
  { c: "General Knowledge", q: "What is the main ingredient in guacamole?", o: ["Tomato", "Avocado", "Onion", "Lime"], a: 1, e: "Avocados are the base ingredient." },
  { c: "General Knowledge", q: "How many continents are there on Earth?", o: ["5", "6", "7", "8"], a: 2, e: "There are 7 continents." },
  { c: "General Knowledge", q: "Who was the first person to walk on the moon?", o: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], a: 2, e: "Neil Armstrong took the first steps in 1969." },
  { c: "General Knowledge", q: "What is the longest river in the world?", o: ["Amazon", "Nile", "Yangtze", "Mississippi"], a: 1, e: "The Nile River is traditionally considered the longest." },
  { c: "General Knowledge", q: "Which gas do plants absorb from the atmosphere?", o: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], a: 2, e: "Plants absorb Carbon Dioxide for photosynthesis." },
  { c: "General Knowledge", q: "Who discovered penicillin?", o: ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Isaac Newton"], a: 1, e: "Alexander Fleming discovered it in 1928." },
  { c: "General Knowledge", q: "What is the capital of Japan?", o: ["Kyoto", "Osaka", "Tokyo", "Seoul"], a: 2, e: "Tokyo is the capital." },
  { c: "General Knowledge", q: "How many bones are in the adult human body?", o: ["206", "210", "195", "215"], a: 0, e: "There are 206 bones in an adult human." },
  { c: "General Knowledge", q: "Which country gifted the Statue of Liberty to the USA?", o: ["UK", "Spain", "France", "Italy"], a: 2, e: "France gifted it in 1886." },
  { c: "General Knowledge", q: "What is the speed of light?", o: ["~300,000 km/s", "~150,000 km/s", "~400,000 km/s", "~200,000 km/s"], a: 0, e: "Light travels at roughly 299,792 kilometers per second." },
  { c: "General Knowledge", q: "Who developed the theory of relativity?", o: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Galileo Galilei"], a: 2, e: "Albert Einstein." },
  { c: "General Knowledge", q: "Which is the largest internal organ in the human body?", o: ["Heart", "Lungs", "Brain", "Liver"], a: 3, e: "The liver is the largest solid internal organ." },
  { c: "General Knowledge", q: "What is the square root of 144?", o: ["10", "12", "14", "16"], a: 1, e: "12 x 12 = 144." },
  { c: "General Knowledge", q: "Which language has the most native speakers?", o: ["English", "Spanish", "Hindi", "Mandarin Chinese"], a: 3, e: "Mandarin Chinese has nearly a billion native speakers." },
  { c: "General Knowledge", q: "In what year did World War II end?", o: ["1943", "1945", "1947", "1950"], a: 1, e: "WWII ended in 1945." },
  { c: "General Knowledge", q: "What is the currency of the United Kingdom?", o: ["Euro", "Pound Sterling", "Franc", "Krone"], a: 1, e: "The Pound Sterling." },
  { c: "General Knowledge", q: "Which planet is closest to the Sun?", o: ["Venus", "Earth", "Mars", "Mercury"], a: 3, e: "Mercury is the closest planet." },
  { c: "General Knowledge", q: "What is the chemical symbol for water?", o: ["HO", "H2O", "CO2", "O2"], a: 1, e: "H2O (Two hydrogen, one oxygen)." },
  { c: "General Knowledge", q: "Who is the author of the Harry Potter series?", o: ["J.R.R. Tolkien", "C.S. Lewis", "J.K. Rowling", "George R.R. Martin"], a: 2, e: "J.K. Rowling." },
  { c: "General Knowledge", q: "What is the largest desert in the world (by area)?", o: ["Sahara", "Arabian", "Gobi", "Antarctic Desert"], a: 3, e: "The Antarctic Desert is the largest, as deserts are defined by precipitation." },
  { c: "General Knowledge", q: "Which bird is known for its beautiful tail feathers?", o: ["Eagle", "Peacock", "Swan", "Flamingo"], a: 1, e: "The Peacock." },
  { c: "General Knowledge", q: "What is the capital of Canada?", o: ["Toronto", "Vancouver", "Ottawa", "Montreal"], a: 2, e: "Ottawa." },
  { c: "General Knowledge", q: "Who invented the telephone?", o: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], a: 2, e: "Alexander Graham Bell." },
  { c: "General Knowledge", q: "What is the national flower of Japan?", o: ["Rose", "Lotus", "Cherry Blossom", "Tulip"], a: 2, e: "The Cherry Blossom (Sakura)." },
  { c: "General Knowledge", q: "Which continent is known as the 'Dark Continent' historically?", o: ["Asia", "Africa", "South America", "Antarctica"], a: 1, e: "Africa was historically referred to as this by European explorers." },
  { c: "General Knowledge", q: "What is the boiling point of water in Celsius?", o: ["50", "90", "100", "120"], a: 2, e: "100 degrees Celsius at sea level." },
  { c: "General Knowledge", q: "Who was the 16th President of the United States?", o: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "Theodore Roosevelt"], a: 2, e: "Abraham Lincoln." },
  { c: "General Knowledge", q: "What is the main gas found in the air we breathe?", o: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], a: 2, e: "Nitrogen makes up about 78% of Earth's atmosphere." },
  { c: "General Knowledge", q: "Which ocean is the Bermuda Triangle located in?", o: ["Pacific", "Atlantic", "Indian", "Arctic"], a: 1, e: "The Atlantic Ocean." },
  { c: "General Knowledge", q: "What is the largest land animal?", o: ["Rhinoceros", "Hippopotamus", "Giraffe", "African Elephant"], a: 3, e: "The African Elephant." },
  { c: "General Knowledge", q: "Who painted the Sistine Chapel ceiling?", o: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], a: 1, e: "Michelangelo." },
  { c: "General Knowledge", q: "What is the chemical formula for table salt?", o: ["NaCl", "KCl", "NaOH", "HCl"], a: 0, e: "Sodium Chloride (NaCl)." },
  { c: "General Knowledge", q: "Which country has the most islands?", o: ["Indonesia", "Philippines", "Sweden", "Canada"], a: 2, e: "Sweden has over 260,000 islands." },
  { c: "General Knowledge", q: "Who wrote 'The Odyssey'?", o: ["Sophocles", "Homer", "Aristotle", "Plato"], a: 1, e: "Homer." },
  { c: "General Knowledge", q: "What is the largest bone in the human body?", o: ["Femur", "Tibia", "Humerus", "Fibula"], a: 0, e: "The Femur (thigh bone)." },
  { c: "General Knowledge", q: "Which animal is the fastest land mammal?", o: ["Lion", "Cheetah", "Gazelle", "Leopard"], a: 1, e: "The Cheetah." },
  { c: "General Knowledge", q: "What is the hardest rock?", o: ["Granite", "Diamond", "Quartz", "Marble"], a: 1, e: "Diamond (technically a mineral, but often grouped in general hardness)." },
  { c: "General Knowledge", q: "In what country is the Great Pyramid of Giza located?", o: ["Greece", "Italy", "Egypt", "Mexico"], a: 2, e: "Egypt." }
];

const GK_QUESTIONS = gk_raw.map(q => ({
  category: q.c,
  categoryColor: "#FFCC00",
  question: q.q,
  options: q.o,
  correctIndex: q.a,
  explanation: q.e,
  imageUrl: q.i,
  audioUrl: q.u,
  points: 100
}));

module.exports = { GK_QUESTIONS };
