const internet_raw = [
  { c: "Internet Culture", q: "What is the name of the OpenAI chatbot that went viral in late 2022?", o: ["Bard", "Claude", "ChatGPT", "Copilot"], a: 2, e: "ChatGPT." },
  { c: "Internet Culture", q: "What was the original name of Google?", o: ["Googol", "BackRub", "WebSearch", "PageRank"], a: 1, e: "BackRub was Google's first project name." },
  { c: "Internet Culture", q: "What does 'AFK' mean in internet slang?", o: ["A Free Kill", "Away From Keyboard", "Always For Keeps", "Asking For Knowledge"], a: 1, e: "Away From Keyboard." },
  { c: "Internet Culture", q: "Which meme features a Shiba Inu dog staring suspiciously at the camera?", o: ["Grumpy Cat", "Nyan Cat", "Doge", "Cheems"], a: 2, e: "Doge.", i: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=500&q=60" },
  { c: "Internet Culture", q: "Which company bought Twitch in 2014 for $970 million?", o: ["Google", "Microsoft", "Amazon", "Facebook"], a: 2, e: "Amazon." },
  { c: "Internet Culture", q: "What is the maximum character limit for a standard tweet (currently, non-Premium)?", o: ["140", "280", "500", "1000"], a: 1, e: "280 characters." },
  { c: "Internet Culture", q: "Who is the founder of Facebook?", o: ["Bill Gates", "Mark Zuckerberg", "Jeff Bezos", "Steve Jobs"], a: 1, e: "Mark Zuckerberg." },
  { c: "Internet Culture", q: "What does 'TL;DR' stand for?", o: ["Too Long; Didn't Read", "Too Late; Didn't Reply", "The Last; Dark Room", "Truth Lies; Don't React"], a: 0, e: "Too Long; Didn't Read." },
  { c: "Internet Culture", q: "What is the name of the rickrolling song?", o: ["Together Forever", "Never Gonna Give You Up", "Wake Me Up Before You Go-Go", "Take On Me"], a: 1, e: "Rick Astley's 'Never Gonna Give You Up'." },
  { c: "Internet Culture", q: "Which social media platform is famous for disappearing photos?", o: ["Instagram", "Snapchat", "TikTok", "Pinterest"], a: 1, e: "Snapchat." },
  { c: "Internet Culture", q: "What meme features a man pointing to his head, suggesting a smart (but silly) idea?", o: ["Drake Hotline Bling", "Roll Safe (Think About It)", "Distracted Boyfriend", "Galaxy Brain"], a: 1, e: "Roll Safe." },
  { c: "Internet Culture", q: "Which app popularized the short-form video format before TikTok?", o: ["Instagram", "Snapchat", "Vine", "Keek"], a: 2, e: "Vine." },
  { c: "Internet Culture", q: "What does 'F' in the chat mean?", o: ["Fail", "Pay Respects", "Fake", "Fix"], a: 1, e: "Derived from Call of Duty: 'Press F to pay respects'." },
  { c: "Internet Culture", q: "What is the name of Apple's virtual assistant?", o: ["Alexa", "Cortana", "Siri", "Bixby"], a: 2, e: "Siri." },
  { c: "Internet Culture", q: "What is the name of the frog meme often used in internet forums?", o: ["Dat Boi", "Pepe", "Kermit", "Crazy Frog"], a: 1, e: "Pepe the Frog." },
  { c: "Internet Culture", q: "What does the internet acronym 'GOAT' stand for?", o: ["Greatest of All Time", "Go Out And Try", "Group of All Teens", "General Office Action Team"], a: 0, e: "Greatest of All Time." },
  { c: "Internet Culture", q: "Which video sharing platform launched in 2020 as a direct competitor to TikTok?", o: ["Instagram Reels", "YouTube Shorts", "Triller", "Vine 2"], a: 1, e: "YouTube Shorts." },
  { c: "Internet Culture", q: "What is the name of the meme where a guy looks back at another girl while holding hands with his girlfriend?", o: ["Drake Meme", "Distracted Boyfriend", "Roll Safe", "Mocking SpongeBob"], a: 1, e: "Distracted Boyfriend." },
  { c: "Internet Culture", q: "In what year was YouTube founded?", o: ["2003", "2005", "2007", "2009"], a: 1, e: "2005." },
  { c: "Internet Culture", q: "What is the name of the first video ever uploaded to YouTube?", o: ["Charlie bit my finger", "Me at the zoo", "Numa Numa", "Evolution of Dance"], a: 1, e: "'Me at the zoo' by Jawed Karim." },
  { c: "Internet Culture", q: "Which internet currency has a Shiba Inu dog as its logo?", o: ["Bitcoin", "Ethereum", "Dogecoin", "Cardano"], a: 2, e: "Dogecoin." },
  { c: "Internet Culture", q: "What does 'Lmao' stand for?", o: ["Laughing my apples off", "Laughing my ass off", "Like my awesome opinion", "Let me ask others"], a: 1, e: "Laughing my ass off." },
  { c: "Internet Culture", q: "Which video went viral as the first to hit 1 billion views on YouTube?", o: ["Baby", "Gangnam Style", "Despacito", "Charlie Bit My Finger"], a: 1, e: "PSY's Gangnam Style in 2012." },
  { c: "Internet Culture", q: "What is the term for hiding easter eggs or hidden messages in software or media?", o: ["Hacking", "Easter Eggs", "Bugs", "Glitch"], a: 1, e: "Easter Eggs." },
  { c: "Internet Culture", q: "What does the slang term 'simp' describe?", o: ["A simple person", "Someone who does way too much for a person they like", "A software programmer", "A game winner"], a: 1, e: "Someone who goes above and beyond for their crush." },

  // Additional 25 Internet Culture / Meme questions
  { c: "Internet Culture", q: "What was the viral challenge in 2014 where people dumped freezing water on themselves?", o: ["Harlem Shake", "Mannequin Challenge", "Ice Bucket Challenge", "Planking"], a: 2, e: "The ALS Ice Bucket Challenge raised millions for charity." },
  { c: "Internet Culture", q: "Which meme depicts a cartoon dog sitting in a room engulfed in flames?", o: ["This is Fine", "Doge", "Grumpy Cat", "Pepe"], a: 0, e: "The 'This is Fine' dog meme created by KC Green." },
  { c: "Internet Culture", q: "What does the acronym 'YOLO' stand for?", o: ["You Only Love Once", "You Only Live Once", "Your Opinions Look Old", "Young Ones Love Others"], a: 1, e: "You Only Live Once, popularized by Drake in 2011." },
  { c: "Internet Culture", q: "Which video features a baby biting his older brother's finger?", o: ["Numa Numa", "Charlie bit my finger", "David After Dentist", "Baby Shark"], a: 1, e: "Charlie bit my finger - one of early YouTube's biggest hits." },
  { c: "Internet Culture", q: "What does the acronym 'FOMO' mean?", o: ["Fear of Missing Out", "Fear of Moving On", "Find Our Main Objective", "Future of Mobile Operations"], a: 0, e: "Fear of Missing Out." },
  { c: "Internet Culture", q: "Which meme features a cat with a grumpy facial expression?", o: ["Nyan Cat", "Keyboard Cat", "Grumpy Cat", "Smudge"], a: 2, e: "Grumpy Cat (real name Tardar Sauce) went viral in 2012." },
  { c: "Internet Culture", q: "What internet phenomenon involves groups of people suddenly gathering in public to perform a dance?", o: ["Planking", "Flash Mob", "Mannequin Challenge", "Tebowing"], a: 1, e: "Flash Mobs." },
  { c: "Internet Culture", q: "What was the viral dance style popularized by Psy in 2012?", o: ["The Floss", "Gangnam Style", "The Whip", "Dab"], a: 1, e: "The horse-riding dance in Gangnam Style." },
  { c: "Internet Culture", q: "What does the slang word 'Flex' mean?", o: ["To stretch", "To show off", "To run away", "To break something"], a: 1, e: "To flex means to show off your achievements or possessions." },
  { c: "Internet Culture", q: "Which viral video involves a young boy high on anesthesia after a checkup?", o: ["Charlie bit my finger", "David After Dentist", "Chocolate Rain", "Sneezing Panda"], a: 1, e: "'David After Dentist' ('Is this real life?')." },
  { c: "Internet Culture", q: "What does the internet slang term 'Noob' mean?", o: ["A professional player", "A beginner or inexperienced player", "A computer hacker", "A friendly user"], a: 1, e: "Noob (from newbie) means a beginner." },
  { c: "Internet Culture", q: "Which meme involves mockingly repeating someone's words in alternating uppercase/lowercase?", o: ["Mocking SpongeBob", "Distracted Boyfriend", "Arthur's Fist", "Galaxy Brain"], a: 0, e: "Mocking SpongeBob (e.g., 'mOcKiNg sPoNgEbOb')." },
  { c: "Internet Culture", q: "What does 'IMO' stand for in chat shorthand?", o: ["In My Opinion", "In Many Offices", "Internet Media Option", "I Must Object"], a: 0, e: "In My Opinion." },
  { c: "Internet Culture", q: "Which YouTube musician went viral with the deep-voiced song 'Chocolate Rain'?", o: ["Tay Zonday", "Bo Burnham", "Marc Rebillet", "Rebecca Black"], a: 0, e: "Tay Zonday posted Chocolate Rain in 2007." },
  { c: "Internet Culture", q: "What does the term 'Clickbait' refer to?", o: ["Fishing software", "Sensationalized headlines designed to attract clicks", "A type of computer virus", "An online ad-blocker"], a: 1, e: "Sensational or misleading headlines to gain views." },
  { c: "Internet Culture", q: "Which Friday-themed song by Rebecca Black became viral as a 'worst song ever' in 2011?", o: ["Friday", "Saturday", "My Weekend", "Fun Day"], a: 0, e: "Rebecca Black's 'Friday'." },
  { c: "Internet Culture", q: "What does 'SMH' stand for?", o: ["Shaking My Head", "So Much Hate", "Send More Help", "Show Me How"], a: 0, e: "Shaking My Head (expressing disappointment)." },
  { c: "Internet Culture", q: "Which meme depicts a grey cat looking at fruit or salad while being yelled at?", o: ["Grumpy Cat", "Smudge the Cat", "Nyan Cat", "Keyboard Cat"], a: 1, e: "Smudge the Cat is the star of the 'Woman Yelling at a Cat' meme." },
  { c: "Internet Culture", q: "What is the slang term for an internet user who intentionally starts arguments?", o: ["Spammer", "Troll", "Bot", "Hacker"], a: 1, e: "A Troll posts inflammatory or off-topic messages." },
  { c: "Internet Culture", q: "What does 'ELI5' mean on forums like Reddit?", o: ["Explain Like I'm 5", "Everyone Likes Internet 5", "Every Logical Idea 5", "Edit Line Index 5"], a: 0, e: "Explain Like I'm 5 (simplify a complex topic)." },
  { c: "Internet Culture", q: "Which meme features a kid in a green shirt clenching his fist on a beach?", o: ["Success Kid", "Bad Luck Brian", "First World Problems", "Scumbag Steve"], a: 0, e: "Success Kid (real name Sammy Griner)." },
  { c: "Internet Culture", q: "What is the name of the viral song and animation of a cat with a pop-tart body flying through space?", o: ["Pop Tart Cat", "Nyan Cat", "Space Cat", "Rainbow Kitty"], a: 1, e: "Nyan Cat." },
  { c: "Internet Culture", q: "What does the slang term 'Glow Up' mean?", o: ["To turn on a light", "A major positive transformation in appearance or style", "To get angry", "To go to sleep"], a: 1, e: "Glow Up refers to a significant glow-up transformation." },
  { c: "Internet Culture", q: "Which social platform was shut down by Twitter in 2017 after popularizing 6-second video loops?", o: ["Vine", "Keek", "Dubsmash", "Periscope"], a: 0, e: "Vine." },
  { c: "Internet Culture", q: "What is the standard reaction to a joke that went over someone's head?", o: ["/s", "r/whoosh", "L", "F"], a: 1, e: "r/whoosh represents the sound of the joke flying over their head." }
];

const INTERNET_QUESTIONS = internet_raw.map(q => ({
  category: q.c,
  categoryColor: "#FF2ADF",
  question: q.q,
  options: q.o,
  correctIndex: q.a,
  explanation: q.e,
  imageUrl: q.i,
  points: 100
}));

module.exports = { INTERNET_QUESTIONS };
