const tech_raw = [
  { c: "Tech & Programming", q: "What does HTTP stand for?", o: ["HyperText Transfer Protocol", "HyperText Transmission Process", "Hyperlink Transfer Technology", "HyperText Transfer Protocol Secure"], a: 0, e: "HyperText Transfer Protocol is the foundation of data communication on the web." },
  { c: "Tech & Programming", q: "Which programming language was created by Brendan Eich in just 10 days?", o: ["Python", "Java", "JavaScript", "C++"], a: 2, e: "JavaScript was created in 10 days in 1995 for Netscape.", i: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=500&q=60" },
  { c: "Tech & Programming", q: "What was the name of the first widely used web browser?", o: ["Internet Explorer", "Netscape Navigator", "Mosaic", "Opera"], a: 2, e: "NCSA Mosaic, released in 1993, popularized the World Wide Web." },
  { c: "Tech & Programming", q: "What does 'URL' stand for?", o: ["Universal Resource Locator", "Uniform Resource Locator", "Uniform Reference Link", "Universal Reference Locator"], a: 1, e: "Uniform Resource Locator." },
  { c: "Tech & Programming", q: "Which animal is the mascot for the Linux operating system?", o: ["Cat", "Dog", "Penguin", "Dolphin"], a: 2, e: "Tux the Penguin is the official mascot." },
  { c: "Tech & Programming", q: "In programming, what is a 'bug'?", o: ["An insect", "A feature", "An error or flaw", "A virus"], a: 2, e: "The term was popularized when a moth was found in a relay of the Harvard Mark II in 1947." },
  { c: "Tech & Programming", q: "Which coding language is styled with CSS and structured with HTML?", o: ["Python", "C#", "JavaScript", "PHP"], a: 2, e: "JavaScript is the script engine of the web." },
  { c: "Tech & Programming", q: "What is the command to copy text on Windows?", o: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], a: 0, e: "Ctrl + C copies." },
  { c: "Tech & Programming", q: "What does the 'S' in HTTPS stand for?", o: ["System", "Server", "Secure", "Socket"], a: 2, e: "Secure. It indicates encryption (SSL/TLS)." },
  { c: "Tech & Programming", q: "What year did the iPhone first launch?", o: ["2005", "2007", "2009", "2010"], a: 1, e: "Steve Jobs introduced the first iPhone in 2007." },
  { c: "Tech & Programming", q: "What does 'RAM' stand for?", o: ["Read Access Memory", "Random Access Memory", "Run All Memory", "Read And Modify"], a: 1, e: "Random Access Memory is short-term volatile memory." },
  { c: "Tech & Programming", q: "Which company makes the GeForce series of graphics cards?", o: ["AMD", "Intel", "NVIDIA", "ASUS"], a: 2, e: "NVIDIA produces the GeForce GPUs." },
  { c: "Tech & Programming", q: "What is the name of the first computer programmer?", o: ["Alan Turing", "Ada Lovelace", "Grace Hopper", "Charles Babbage"], a: 1, e: "Ada Lovelace wrote the first algorithm for Babbage's Analytical Engine." },
  { c: "Tech & Programming", q: "What error code represents 'Not Found' on the web?", o: ["400", "403", "404", "500"], a: 2, e: "404 Not Found." },
  { c: "Tech & Programming", q: "Which company created the React JavaScript library?", o: ["Google", "Facebook (Meta)", "Microsoft", "Twitter"], a: 1, e: "Facebook developed React in 2013." },
  { c: "Tech & Programming", q: "What is the default port for HTTP?", o: ["21", "22", "80", "443"], a: 2, e: "Port 80 is HTTP, 443 is HTTPS." },
  { c: "Tech & Programming", q: "What does 'GPU' stand for?", o: ["Graphical Process Unit", "Graphics Processing Unit", "General Processing Unit", "Gaming Power Unit"], a: 1, e: "Graphics Processing Unit." },
  { c: "Tech & Programming", q: "Which tech giant bought GitHub in 2018?", o: ["Google", "Amazon", "Apple", "Microsoft"], a: 3, e: "Microsoft acquired GitHub for $7.5 billion." },
  { c: "Tech & Programming", q: "What is the most popular version control system?", o: ["SVN", "Mercurial", "Git", "CVS"], a: 2, e: "Git, created by Linus Torvalds." },
  { c: "Tech & Programming", q: "What does 'API' stand for?", o: ["Application Programming Interface", "Advanced Program Integration", "Automated Process Interface", "Application Process Interface"], a: 0, e: "Application Programming Interface." },
  { c: "Tech & Programming", q: "What does the 'www' in a website address stand for?", o: ["World Wide Web", "World Web Wide", "Web World Wide", "Wide World Web"], a: 0, e: "World Wide Web, invented by Tim Berners-Lee." },
  { c: "Tech & Programming", q: "Which company developed the Android operating system before Google bought it?", o: ["Samsung", "Nokia", "Android Inc.", "HTC"], a: 2, e: "Android Inc., co-founded by Andy Rubin." },
  { c: "Tech & Programming", q: "What is the standard data format used by most web APIs today?", o: ["XML", "JSON", "CSV", "YAML"], a: 1, e: "JavaScript Object Notation (JSON)." },
  { c: "Tech & Programming", q: "What does 'HTML' stand for?", o: ["HyperText Markup Language", "HyperTech Machine Language", "HighText Markup Language", "HyperText Multiple Language"], a: 0, e: "HyperText Markup Language." },
  { c: "Tech & Programming", q: "What does 'SSD' stand for in computer storage?", o: ["Solid State Drive", "Super Speed Drive", "Solid Storage Device", "System Storage Drive"], a: 0, e: "Solid State Drive." },
  
  // Additional 25 strictly Tech / Programming questions
  { c: "Tech & Programming", q: "What is the main purpose of SQL?", o: ["Style web pages", "Manage databases", "Compile code", "Design user interfaces"], a: 1, e: "SQL (Structured Query Language) is used to manage relational databases." },
  { c: "Tech & Programming", q: "Which of the following is NOT an object-oriented programming language?", o: ["Java", "C++", "Python", "C"], a: 3, e: "C is a procedural programming language, not object-oriented." },
  { c: "Tech & Programming", q: "What does CPU stand for?", o: ["Computer Processing Unit", "Central Processing Unit", "Central Power Unit", "Core Processing Utility"], a: 1, e: "Central Processing Unit." },
  { c: "Tech & Programming", q: "Which protocol is used to securely transfer files over the internet?", o: ["FTP", "SFTP", "SMTP", "HTTP"], a: 1, e: "SFTP (Secure File Transfer Protocol) uses SSH to encrypt traffic." },
  { c: "Tech & Programming", q: "What is the name of the creator of the Python programming language?", o: ["Guido van Rossum", "Dennis Ritchie", "James Gosling", "Bjarne Stroustrup"], a: 0, e: "Guido van Rossum created Python in 1991." },
  { c: "Tech & Programming", q: "In Java, what is the default value of a boolean variable?", o: ["true", "false", "null", "0"], a: 1, e: "The default value of a boolean primitive in Java is false." },
  { c: "Tech & Programming", q: "What does CSS stand for?", o: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Systems", "Colloquial Style Sheets"], a: 1, e: "Cascading Style Sheets." },
  { c: "Tech & Programming", q: "Which CSS property is used to change the background color of an element?", o: ["color", "background-color", "bgcolor", "background"], a: 1, e: "background-color." },
  { c: "Tech & Programming", q: "What does DNS stand for?", o: ["Data Network System", "Domain Name System", "Dynamic Name Service", "Domain Network Server"], a: 1, e: "Domain Name System maps domain names to IP addresses." },
  { c: "Tech & Programming", q: "Which company created the C# programming language?", o: ["Microsoft", "Oracle", "Sun Microsystems", "Apple"], a: 0, e: "Microsoft created C# in 2000 as part of its .NET initiative." },
  { c: "Tech & Programming", q: "In web development, what does the 'DOM' stand for?", o: ["Data Object Model", "Document Object Model", "Domain Object Management", "Document Output Module"], a: 1, e: "Document Object Model." },
  { c: "Tech & Programming", q: "What is the name of the first computer virus?", o: ["Creeper", "MyDoom", "ILOVEYOU", "Melissa"], a: 0, e: "The Creeper worm, written in 1971, is widely considered the first computer virus." },
  { c: "Tech & Programming", q: "What is the binary representation of the decimal number 10?", o: ["1001", "1010", "1100", "1111"], a: 1, e: "1010 in binary (8 + 2) equals 10 in decimal." },
  { c: "Tech & Programming", q: "Which programming language is mainly used for iOS app development (modern)?", o: ["Objective-C", "Swift", "Java", "Kotlin"], a: 1, e: "Swift is Apple's modern language for iOS and macOS apps." },
  { c: "Tech & Programming", q: "What does 'SaaS' stand for?", o: ["Software as a Service", "System as a Service", "Security as a System", "Software as a System"], a: 0, e: "Software as a Service." },
  { c: "Tech & Programming", q: "Which of the following is a non-relational (NoSQL) database?", o: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], a: 2, e: "MongoDB is a document-oriented NoSQL database." },
  { c: "Tech & Programming", q: "What is the purpose of a compiler?", o: ["To run code directly", "To translate source code into machine code", "To design layouts", "To test UI components"], a: 1, e: "Compilers translate high-level programming language into machine code." },
  { c: "Tech & Programming", q: "Which port is used by default for secure shell (SSH) connections?", o: ["21", "22", "23", "80"], a: 1, e: "Port 22 is the standard port for SSH." },
  { c: "Tech & Programming", q: "In JavaScript, what operator is used for strict equality comparison?", o: ["=", "==", "===", "!=="], a: 2, e: "=== compares both value and type." },
  { c: "Tech & Programming", q: "What does 'WYSIWYG' stand for?", o: ["What You See Is What You Get", "Why You See Is Why You Go", "Web Yield System In Windows Group", "What You Send Is What You Get"], a: 0, e: "What You See Is What You Get refers to visual editors." },
  { c: "Tech & Programming", q: "Which data structure operates on a Last-In, First-Out (LIFO) basis?", o: ["Queue", "Stack", "Linked List", "Tree"], a: 1, e: "Stacks operate on LIFO (like a stack of plates)." },
  { c: "Tech & Programming", q: "What does IP stand for in 'IP Address'?", o: ["Intranet Protocol", "Internet Protocol", "Information Protocol", "Internal Protocol"], a: 1, e: "Internet Protocol." },
  { c: "Tech & Programming", q: "What is the name of Google's mobile operating system?", o: ["ChromeOS", "Android", "Fuchsia", "iOS"], a: 1, e: "Android." },
  { c: "Tech & Programming", q: "In Python, which keyword is used to define a function?", o: ["func", "function", "def", "define"], a: 2, e: "The 'def' keyword is used to define functions in Python." },
  { c: "Tech & Programming", q: "What is the term for resolving errors in code?", o: ["Compiling", "Refactoring", "Debugging", "Parsing"], a: 2, e: "Debugging is the process of identifying and removing bugs." }
];

const TECH_QUESTIONS = tech_raw.map(q => ({
  category: q.c,
  categoryColor: "#00E5FF",
  question: q.q,
  options: q.o,
  correctIndex: q.a,
  explanation: q.e,
  imageUrl: q.i,
  points: 100
}));

module.exports = { TECH_QUESTIONS };
