const tech_raw = [
  { c: "Tech & Internet Culture", q: "What does HTTP stand for?", o: ["HyperText Transfer Protocol", "HyperText Transmission Process", "Hyperlink Transfer Technology", "HyperText Transfer Protocol Secure"], a: 0, e: "HyperText Transfer Protocol is the foundation of data communication for the World Wide Web." },
  { c: "Tech & Internet Culture", q: "Which programming language was created by Brendan Eich in just 10 days?", o: ["Python", "Java", "JavaScript", "C++"], a: 2, e: "JavaScript was created in 10 days in 1995.", i: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=500&q=60" },
  { c: "Tech & Internet Culture", q: "What was the name of the first widely used web browser?", o: ["Internet Explorer", "Netscape Navigator", "Mosaic", "Opera"], a: 2, e: "NCSA Mosaic, released in 1993, popularized the World Wide Web." },
  { c: "Tech & Internet Culture", q: "What does 'URL' stand for?", o: ["Universal Resource Locator", "Uniform Resource Locator", "Uniform Reference Link", "Universal Reference Locator"], a: 1, e: "Uniform Resource Locator." },
  { c: "Tech & Internet Culture", q: "What was the original name of Google?", o: ["Googol", "BackRub", "WebSearch", "PageRank"], a: 1, e: "Larry Page and Sergey Brin originally called their search engine BackRub." },
  { c: "Tech & Internet Culture", q: "Which animal is the mascot for the Linux operating system?", o: ["Cat", "Dog", "Penguin", "Dolphin"], a: 2, e: "Tux the Penguin is the official mascot." },
  { c: "Tech & Internet Culture", q: "In programming, what is a 'bug'?", o: ["An insect", "A feature", "An error or flaw", "A virus"], a: 2, e: "The term was popularized when an actual moth was found in a computer in 1947." },
  { c: "Tech & Internet Culture", q: "What is the name of the cryptocurrency created by 'Satoshi Nakamoto'?", o: ["Ethereum", "Dogecoin", "Bitcoin", "Litecoin"], a: 2, e: "Bitcoin was created in 2009 by an unknown person using this pseudonym." },
  { c: "Tech & Internet Culture", q: "What does 'AFK' mean in internet slang?", o: ["A Free Kill", "Away From Keyboard", "Always For Keeps", "Asking For Knowledge"], a: 1, e: "Away From Keyboard." },
  { c: "Tech & Internet Culture", q: "Which meme features a Shiba Inu dog staring at the camera?", o: ["Grumpy Cat", "Nyan Cat", "Doge", "Cheems"], a: 2, e: "Doge became a massive internet phenomenon and inspired Dogecoin." },
  { c: "Tech & Internet Culture", q: "What is the famous internet rule that states 'If it exists, there is p*rn of it'?", o: ["Rule 34", "Rule 42", "Rule 1", "Rule 63"], a: 0, e: "Rule 34 of the internet." },
  { c: "Tech & Internet Culture", q: "Which company bought Twitch in 2014 for $970 million?", o: ["Google", "Microsoft", "Amazon", "Facebook"], a: 2, e: "Amazon acquired Twitch." },
  { c: "Tech & Internet Culture", q: "What is the maximum character limit for a standard tweet (currently, non-Blue)?", o: ["140", "280", "500", "1000"], a: 1, e: "Twitter doubled the limit from 140 to 280 in 2017." },
  { c: "Tech & Internet Culture", q: "Who is the CEO of Tesla and SpaceX?", o: ["Jeff Bezos", "Bill Gates", "Mark Zuckerberg", "Elon Musk"], a: 3, e: "Elon Musk." },
  { c: "Tech & Internet Culture", q: "What does 'TL;DR' stand for?", o: ["Too Long; Didn't Read", "Too Late; Didn't Reply", "The Last; Dark Room", "Truth Lies; Don't React"], a: 0, e: "Used to summarize a long post." },
  { c: "Tech & Internet Culture", q: "What is the name of the rickrolling song?", o: ["Together Forever", "Never Gonna Give You Up", "Wake Me Up Before You Go-Go", "Take On Me"], a: 1, e: "Rick Astley's 'Never Gonna Give You Up'." },
  { c: "Tech & Internet Culture", q: "Which coding language is styled with CSS and structured with HTML?", o: ["Python", "C#", "JavaScript", "PHP"], a: 2, e: "JavaScript is the third core technology of the web." },
  { c: "Tech & Internet Culture", q: "What is the command to copy text on Windows?", o: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], a: 0, e: "Ctrl + C copies." },
  { c: "Tech & Internet Culture", q: "What does the 'S' in HTTPS stand for?", o: ["System", "Server", "Secure", "Socket"], a: 2, e: "Secure. It means the connection is encrypted." },
  { c: "Tech & Internet Culture", q: "Which social media platform is famous for disappearing photos?", o: ["Instagram", "Snapchat", "TikTok", "Pinterest"], a: 1, e: "Snapchat pioneered the disappearing photo format." },
  { c: "Tech & Internet Culture", q: "What year did the iPhone first launch?", o: ["2005", "2007", "2009", "2010"], a: 1, e: "Steve Jobs unveiled the original iPhone in 2007." },
  { c: "Tech & Internet Culture", q: "What does 'RAM' stand for?", o: ["Read Access Memory", "Random Access Memory", "Run All Memory", "Read And Modify"], a: 1, e: "Random Access Memory is short-term computer memory." },
  { c: "Tech & Internet Culture", q: "Which company makes the GeForce series of graphics cards?", o: ["AMD", "Intel", "NVIDIA", "ASUS"], a: 2, e: "NVIDIA produces the GeForce lineup." },
  { c: "Tech & Internet Culture", q: "What is the name of the first computer programmer?", o: ["Alan Turing", "Ada Lovelace", "Grace Hopper", "Charles Babbage"], a: 1, e: "Ada Lovelace wrote the first algorithm for Babbage's Analytical Engine." },
  { c: "Tech & Internet Culture", q: "What error code represents 'Not Found' on the web?", o: ["400", "403", "404", "500"], a: 2, e: "404 Not Found." },
  { c: "Tech & Internet Culture", q: "Which company created the React JavaScript library?", o: ["Google", "Facebook (Meta)", "Microsoft", "Twitter"], a: 1, e: "Facebook developed React internally." },
  { c: "Tech & Internet Culture", q: "What is the default port for HTTP?", o: ["21", "22", "80", "443"], a: 2, e: "Port 80 is HTTP, 443 is HTTPS." },
  { c: "Tech & Internet Culture", q: "What meme features a man pointing to his head, suggesting a smart idea?", o: ["Drake Hotline Bling", "Roll Safe (Think About It)", "Distracted Boyfriend", "Galaxy Brain"], a: 1, e: "The 'Roll Safe' meme." },
  { c: "Tech & Internet Culture", q: "What video game distribution platform is owned by Valve?", o: ["Origin", "Epic Games Store", "Steam", "GOG"], a: 2, e: "Steam." },
  { c: "Tech & Internet Culture", q: "What is the term for a malicious program disguised as legitimate software?", o: ["Worm", "Trojan Horse", "Ransomware", "Spyware"], a: 1, e: "A Trojan Horse." },
  { c: "Tech & Internet Culture", q: "What does 'GPU' stand for?", o: ["Graphical Process Unit", "Graphics Processing Unit", "General Processing Unit", "Gaming Power Unit"], a: 1, e: "Graphics Processing Unit." },
  { c: "Tech & Internet Culture", q: "Which tech giant bought GitHub in 2018?", o: ["Google", "Amazon", "Apple", "Microsoft"], a: 3, e: "Microsoft acquired GitHub for $7.5 billion." },
  { c: "Tech & Internet Culture", q: "What is the most popular version control system?", o: ["SVN", "Mercurial", "Git", "CVS"], a: 2, e: "Git, created by Linus Torvalds." },
  { c: "Tech & Internet Culture", q: "What does 'API' stand for?", o: ["Application Programming Interface", "Advanced Program Integration", "Automated Process Interface", "Application Process Interface"], a: 0, e: "Application Programming Interface." },
  { c: "Tech & Internet Culture", q: "What is the name of OpenAI's popular language model chatbot?", o: ["Bard", "Claude", "ChatGPT", "Copilot"], a: 2, e: "ChatGPT." },
  { c: "Tech & Internet Culture", q: "What does the 'www' in a website address stand for?", o: ["World Wide Web", "World Web Wide", "Web World Wide", "Wide World Web"], a: 0, e: "World Wide Web, invented by Tim Berners-Lee." },
  { c: "Tech & Internet Culture", q: "Which meme features a cat sitting at a table with vegetables being yelled at by women?", o: ["Smudge the Cat", "Grumpy Cat", "Woman Yelling at Cat", "Nyan Cat"], a: 2, e: "The 'Woman Yelling at a Cat' meme features Smudge." },
  { c: "Tech & Internet Culture", q: "What was the first social media network to reach 1 million users?", o: ["Facebook", "MySpace", "Friendster", "Bebo"], a: 2, e: "Friendster achieved this milestone in 2003." },
  { c: "Tech & Internet Culture", q: "Which company developed the Android operating system before Google bought it?", o: ["Samsung", "Nokia", "Android Inc.", "HTC"], a: 2, e: "Android Inc., founded by Andy Rubin." },
  { c: "Tech & Internet Culture", q: "What is the name of the internet phenomenon where a dress appeared blue/black to some and white/gold to others?", o: ["The Dress", "Yanny vs Laurel", "The Color Illusion", "The Viral Dress"], a: 0, e: "Known simply as 'The Dress' (2015)." },
  { c: "Tech & Internet Culture", q: "What is the standard data format used by most web APIs today?", o: ["XML", "JSON", "CSV", "YAML"], a: 1, e: "JavaScript Object Notation (JSON)." },
  { c: "Tech & Internet Culture", q: "Which app popularized the short-form video format before TikTok?", o: ["Instagram", "Snapchat", "Vine", "Keek"], a: 2, e: "Vine (6-second looping videos)." },
  { c: "Tech & Internet Culture", q: "What does 'F' in the chat mean?", o: ["Fail", "Pay Respects", "Fake", "Fix"], a: 1, e: "From the Call of Duty prompt 'Press F to pay respects'." },
  { c: "Tech & Internet Culture", q: "What is the name of Apple's virtual assistant?", o: ["Alexa", "Cortana", "Siri", "Bixby"], a: 2, e: "Siri." },
  { c: "Tech & Internet Culture", q: "Which company is known for its 'Think Different' slogan?", o: ["IBM", "Apple", "Microsoft", "Intel"], a: 1, e: "Apple." },
  { c: "Tech & Internet Culture", q: "What is the world's most widely used operating system for smartphones?", o: ["iOS", "Android", "Windows Mobile", "Symbian"], a: 1, e: "Android." },
  { c: "Tech & Internet Culture", q: "What does 'HTML' stand for?", o: ["HyperText Markup Language", "HyperTech Machine Language", "HighText Markup Language", "HyperText Multiple Language"], a: 0, e: "HyperText Markup Language." },
  { c: "Tech & Internet Culture", q: "What is the name of the frog meme often used by the internet?", o: ["Dat Boi", "Pepe", "Kermit", "Crazy Frog"], a: 1, e: "Pepe the Frog." },
  { c: "Tech & Internet Culture", q: "What is a 'CAPTCHA' used for?", o: ["Encrypting passwords", "Determining if a user is human", "Catching viruses", "Optimizing search engines"], a: 1, e: "Completely Automated Public Turing test to tell Computers and Humans Apart." },
  { c: "Tech & Internet Culture", q: "What does 'SSD' stand for in computer storage?", o: ["Solid State Drive", "Super Speed Drive", "Solid Storage Device", "System Storage Drive"], a: 0, e: "Solid State Drive." }
];

const TECH_QUESTIONS = tech_raw.map(q => ({
  category: q.c,
  categoryColor: "#00E5FF",
  question: q.q,
  options: q.o,
  correctIndex: q.a,
  explanation: q.e,
  imageUrl: q.i,
  points: 100
}));

module.exports = { TECH_QUESTIONS };
